create table public.athletes (
  member_id character varying(50) not null,
  name character varying(100) not null,
  age integer not null,
  club character varying(100) not null,
  gender character varying(50) not null,
  weight_class character varying(50) not null,
  entry_total integer not null,
  session_number integer null,
  session_platform public.platform_type null,
  meet character varying(255) not null,
  adaptive boolean not null default false,
  constraint athletes_pkey primary key (member_id)
) TABLESPACE pg_default;

create index IF not exists idx_athletes_adaptive on public.athletes using btree (adaptive) TABLESPACE pg_default;

create index IF not exists idx_athletes_session on public.athletes using btree (session_number, session_platform) TABLESPACE pg_default;

create table public.intl_rankings (
  meet text null,
  ranking integer null,
  name text null,
  weight_class text null,
  total integer null,
  percent_a numeric(5, 2) null,
  gender text null,
  age_category text null,
  id bigint generated always as identity not null,
  constraint intl_rankings_pkey primary key (id)
) TABLESPACE pg_default;

create table public.lifting_results (
  id bigint generated by default as identity not null,
  event_id text not null,
  meet text not null,
  date text not null,
  name text not null,
  age text null,
  body_weight numeric null,
  snatch1 numeric null,
  snatch2 numeric null,
  snatch3 numeric null,
  snatch_best numeric null,
  cj1 numeric null,
  cj2 numeric null,
  cj3 numeric null,
  cj_best numeric null,
  total numeric null,
  created_at timestamp with time zone null default now(),
  adaptive boolean not null default false,
  federation text null,
  constraint lifting_results_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_lifting_results_name on public.lifting_results using btree (name) TABLESPACE pg_default;

create index IF not exists idx_lifting_results_meet on public.lifting_results using btree (meet) TABLESPACE pg_default;

create index IF not exists idx_lifting_results_date on public.lifting_results using btree (date) TABLESPACE pg_default;

create index IF not exists idx_lifting_results_total on public.lifting_results using btree (total) TABLESPACE pg_default;

create index IF not exists idx_lifting_results_adaptive on public.lifting_results using btree (adaptive) TABLESPACE pg_default;

create trigger tr_populate_national_rankings
after INSERT
or
update on lifting_results for EACH row
execute FUNCTION populate_national_rankings ();

create table public.meets (
  id uuid not null default gen_random_uuid (),
  name text not null,
  venue_name text not null,
  venue_street text not null,
  venue_city text not null,
  venue_state text not null,
  venue_zip text not null,
  time_zone text not null,
  start_date date not null,
  end_date date not null,
  status public.meet_status not null default 'upcoming'::meet_status,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  federation text null,
  constraint meets_pkey primary key (id),
  constraint meets_name_key unique (name)
) TABLESPACE pg_default;

create trigger update_meets_updated_at BEFORE
update on meets for EACH row
execute FUNCTION update_updated_at_column ();

create table public.notification_preferences (
  id uuid not null default extensions.uuid_generate_v4 (),
  user_id text not null,
  expo_push_token text null,
  notification_enabled boolean not null default true,
  created_at timestamp with time zone not null default CURRENT_TIMESTAMP,
  updated_at timestamp with time zone not null default CURRENT_TIMESTAMP,
  constraint notification_preferences_pkey primary key (id),
  constraint notification_preferences_user_id_key unique (user_id)
) TABLESPACE pg_default;

create index IF not exists idx_notification_preferences_token on public.notification_preferences using btree (expo_push_token) TABLESPACE pg_default;

create trigger on_notification_preferences_updated BEFORE
update on notification_preferences for EACH row
execute FUNCTION handle_updated_at ();

create table public.qualifying_totals (
  id serial not null,
  event_name text not null,
  gender text not null,
  age_category text not null,
  weight_class text not null,
  qualifying_total integer not null,
  created_at timestamp with time zone null default now(),
  constraint qualifying_totals_pkey primary key (id)
) TABLESPACE pg_default;

create table public.records (
  id serial not null,
  record_type text not null,
  age_category text not null,
  gender text not null,
  weight_class text not null,
  snatch_record numeric null,
  cj_record numeric null,
  total_record numeric null,
  created_at timestamp with time zone null default now(),
  constraint records_pkey primary key (id)
) TABLESPACE pg_default;

create table public.saved_sessions (
  id text not null,
  user_id text not null,
  meet text not null,
  session_number integer not null,
  platform text not null,
  weight_class text null,
  start_time text null,
  notes text null,
  athlete_names text[] null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  date date null,
  constraint saved_sessions_pkey primary key (id, user_id)
) TABLESPACE pg_default;

create index IF not exists saved_sessions_user_id_idx on public.saved_sessions using btree (user_id) TABLESPACE pg_default;

create table public.session_schedule (
  id serial not null,
  date date not null,
  session_id integer not null,
  start_time time without time zone not null,
  weigh_in_time time without time zone not null,
  platform character varying(50) not null,
  weight_class character varying(100) not null,
  meet character varying(255) not null,
  constraint session_schedule_pkey primary key (id),
  constraint session_schedule_meet_session_platform_unique unique (meet, session_id, platform),
  constraint session_schedule_unique_key unique (meet, session_id, platform, weight_class)
) TABLESPACE pg_default;

create index IF not exists idx_session_schedule_session_id on public.session_schedule using btree (session_id) TABLESPACE pg_default;

create index IF not exists idx_session_schedule_date on public.session_schedule using btree (date) TABLESPACE pg_default;

create table public.standards (
  id serial not null,
  age_category text not null,
  gender text not null,
  weight_class text not null,
  standard_a integer not null,
  standard_b integer not null default 0,
  created_at timestamp with time zone null default now(),
  constraint standards_pkey primary key (id)
) TABLESPACE pg_default;

create table public.wso_records (
  id serial not null,
  wso text not null,
  age_category text not null,
  gender text not null,
  weight_class text not null,
  snatch_record numeric null,
  cj_record numeric null,
  total_record numeric null,
  created_at timestamp with time zone null default now(),
  constraint wso_records_pkey primary key (id)
) TABLESPACE pg_default;