export type AthletePlacement = {
  adaptive: boolean;
  age: number;
  club: string;
  entryTotal: number;
  gender: string;
  meet: string;
  memberId: string;
  name: string;
  sessionNumber?: number;
  sessionPlatform?: string;
  weightClass: string;
  wso?: string;
};

export const athletePlacements: AthletePlacement[] = [
  {
    adaptive: false,
    age: 34,
    club: "BLACK & RED BARBELL CLUB",
    entryTotal: 135,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1002011",
    name: "Lucy Nguyen",
    sessionNumber: 36,
    sessionPlatform: "White",
    weightClass: "48",
  },
  {
    adaptive: false,
    age: 35,
    club: "HI PERFORMANCE ATHLETICS",
    entryTotal: 170,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1002876",
    name: "Tiffani Lee",
    sessionNumber: 37,
    sessionPlatform: "Red",
    weightClass: "53",
  },
  {
    adaptive: false,
    age: 31,
    club: "1Kilo",
    entryTotal: 170,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1017055",
    name: "Alice McBroom",
    sessionNumber: 37,
    sessionPlatform: "Red",
    weightClass: "53",
  },
  {
    adaptive: false,
    age: 32,
    club: "Southern California Weightlifting Club",
    entryTotal: 165,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1070706",
    name: "Julia Tomasello",
    sessionNumber: 37,
    sessionPlatform: "Red",
    weightClass: "53",
  },
  {
    adaptive: false,
    age: 33,
    club: "Marin Heavy Athletics",
    entryTotal: 150,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1066809",
    name: "Juliana Flynn",
    sessionNumber: 44,
    sessionPlatform: "Red",
    weightClass: "53",
  },
  {
    adaptive: false,
    age: 31,
    club: "PARAMOUNT BARBELL CLUB",
    entryTotal: 145,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1011849",
    name: "Judy Zhou",
    sessionNumber: 44,
    sessionPlatform: "Red",
    weightClass: "53",
  },
  {
    adaptive: false,
    age: 26,
    club: "HASSLE FREE BBC",
    entryTotal: 180,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1073273",
    name: "Jasmine He",
    sessionNumber: 24,
    sessionPlatform: "Blue",
    weightClass: "58",
  },
  {
    adaptive: false,
    age: 33,
    club: "PERFORMANCE ONE WEIGHTLIFTING",
    entryTotal: 170,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1013623",
    name: "norelle justice",
    sessionNumber: 37,
    sessionPlatform: "Blue",
    weightClass: "58",
  },
  {
    adaptive: false,
    age: 20,
    club: "UNIVERSITY OF TEXAS",
    entryTotal: 190,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1079568",
    name: "Eden hansen",
    sessionNumber: 35,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 31,
    club: "HEAVY METAL BARBELL",
    entryTotal: 190,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1024973",
    name: "Danielle Sheppard",
    sessionNumber: 35,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 31,
    club: "DC WEIGHTLIFTING CLUB",
    entryTotal: 185,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "193260",
    name: "Couger Jaramillo",
    sessionNumber: 35,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 41,
    club: "Optimus Barbell Club",
    entryTotal: 185,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1004193",
    name: "Traci Beaune",
    sessionNumber: 35,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 31,
    club: "Seattle Barbell Club",
    entryTotal: 175,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "180041",
    name: "Grayson Corrales",
    sessionNumber: 25,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 35,
    club: "Ritual Weightlifting",
    entryTotal: 176,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1027414",
    name: "Corynne Francis",
    sessionNumber: 25,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 33,
    club: "Southern California Weightlifting Club",
    entryTotal: 175,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1022932",
    name: "anna maguire",
    sessionNumber: 25,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 24,
    club: "Fourteen Forty Collective",
    entryTotal: 220,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1053969",
    name: "Abigail Cooper",
    sessionNumber: 18,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 20,
    club: "Fortified Strength",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1027360",
    name: "Kimberly Wiese",
    sessionNumber: 40,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 31,
    club: "Superfly Barbell Club",
    entryTotal: 203,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1024143",
    name: "Taylor Lucas",
    sessionNumber: 39,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 29,
    club: "PARAMOUNT BARBELL CLUB",
    entryTotal: 200,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1041630",
    name: "Nicola Benfield",
    sessionNumber: 39,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 29,
    club: "Sled-Dog Weightlifting",
    entryTotal: 195,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "222080",
    name: "Riley Stefan",
    sessionNumber: 39,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 30,
    club: "Mako Athletics",
    entryTotal: 185,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1053632",
    name: "Alicia Fernandez",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 32,
    club: "EAST COAST GOLD W/L TEAM",
    entryTotal: 182,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1006540",
    name: "Alexis Danchak",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 38,
    club: "York County Barbell",
    entryTotal: 180,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1027507",
    name: "Elsbeth Paige-Jeffers",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 32,
    club: "Providence Barbell Club",
    entryTotal: 180,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1069790",
    name: "Brittany Panerali",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 28,
    club: "TEAM BLASTOFF",
    entryTotal: 178,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1053929",
    name: "Anna Konrath",
    sessionNumber: 36,
    sessionPlatform: "Red",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 29,
    club: "S&M Strength",
    entryTotal: 163,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1076895",
    name: "Talia Somma",
    sessionNumber: 36,
    sessionPlatform: "Red",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 23,
    club: "Unaffiliated",
    entryTotal: 250,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1000772",
    name: "Olivia Reeves",
    sessionNumber: 41,
    sessionPlatform: "Blue",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 31,
    club: "West Coast Weightlifting",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1073143",
    name: "ivana austhof",
    sessionNumber: 41,
    sessionPlatform: "Blue",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 35,
    club: "Unaffiliated",
    entryTotal: 205,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1014830",
    name: "Shala Giardini",
    sessionNumber: 32,
    sessionPlatform: "White",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 27,
    club: "Vehement Elite Athletics",
    entryTotal: 206,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1061635",
    name: "Christine Yee",
    sessionNumber: 41,
    sessionPlatform: "Blue",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 35,
    club: "Tri State Barbell",
    entryTotal: 191,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1013719",
    name: "Taylor Maginnis",
    sessionNumber: 40,
    sessionPlatform: "Red",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 28,
    club: "Rise Weightlifting",
    entryTotal: 222,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1032566",
    name: "Victoria Jefferson",
    sessionNumber: 42,
    sessionPlatform: "Red",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 30,
    club: "1Kilo",
    entryTotal: 215,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1043067",
    name: "Kateri Peters",
    sessionNumber: 42,
    sessionPlatform: "Red",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 33,
    club: "Vardanian Weightlifting",
    entryTotal: 205,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1038740",
    name: "Alexandria Fillmore",
    sessionNumber: 40,
    sessionPlatform: "White",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 23,
    club: "Heroic Barbell",
    entryTotal: 200,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1079277",
    name: "maicee Bradley",
    sessionNumber: 40,
    sessionPlatform: "White",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 34,
    club: "Providence Barbell Club",
    entryTotal: 190,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1020890",
    name: "Sydney Collins",
    sessionNumber: 34,
    sessionPlatform: "Red",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 39,
    club: "Catalyst Masters",
    entryTotal: 175,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1034283",
    name: "Mary Quigley",
    sessionNumber: 31,
    sessionPlatform: "White",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 44,
    club: "CALAVERA BARBELL",
    entryTotal: 175,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "208662",
    name: "Amanda Cook",
    sessionNumber: 31,
    sessionPlatform: "White",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 33,
    club: "Marin Heavy Athletics",
    entryTotal: 220,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1056122",
    name: "Brittany Latham",
    sessionNumber: 45,
    sessionPlatform: "Blue",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 35,
    club: "BASA Weightlifting",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1078881",
    name: "Moriah Young",
    sessionNumber: 45,
    sessionPlatform: "Blue",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 32,
    club: "CHFP WEIGHTLIFTING CLUB",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1059189",
    name: "Kiara Earle",
    sessionNumber: 45,
    sessionPlatform: "Blue",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 29,
    club: "NorCal Weightlifting",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1074159",
    name: "Hannah Wheeler",
    sessionNumber: 45,
    sessionPlatform: "Blue",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 45,
    club: "Catalyst Masters",
    entryTotal: 200,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1045014",
    name: "Kimberlee Douglas",
    sessionNumber: 34,
    sessionPlatform: "Red",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 30,
    club: "Southern California Weightlifting Club",
    entryTotal: 203,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1066211",
    name: "Haley Heard",
    sessionNumber: 43,
    sessionPlatform: "White",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 39,
    club: "Waxman's Gym",
    entryTotal: 195,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1082639",
    name: "Abigail Lundquist",
    sessionNumber: 34,
    sessionPlatform: "Red",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 32,
    club: "Unaffiliated",
    entryTotal: 187,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1077935",
    name: "Kristen Dudley",
    sessionNumber: 34,
    sessionPlatform: "Red",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 30,
    club: "HASSLE FREE BBC",
    entryTotal: 240,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "197508",
    name: "Matthew Yung",
    sessionNumber: 35,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 30,
    club: "BARBARIAN BARBELL CLUB",
    entryTotal: 240,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1009707",
    name: "Jeffrey Suarez",
    sessionNumber: 35,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 32,
    club: "Unaffiliated",
    entryTotal: 227,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1030746",
    name: "Angelo Kelly",
    sessionNumber: 25,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 22,
    club: "VERO BEACH WEIGHTLIFTING",
    entryTotal: 227,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1066761",
    name: "Braylen Lopez",
    sessionNumber: 25,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 38,
    club: "Rising Tide Weightlifting",
    entryTotal: 270,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "140636",
    name: "Travis Cooper",
    sessionNumber: 36,
    sessionPlatform: "Blue",
    weightClass: "71",
  },
  {
    adaptive: false,
    age: 23,
    club: "Texas A&M Aggie Weightlifting",
    entryTotal: 275,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1072145",
    name: "Jordan McKenzie",
    sessionNumber: 30,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 45,
    club: "PARAMOUNT BARBELL CLUB",
    entryTotal: 275,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "188287",
    name: "Christopher Douglas",
    sessionNumber: 30,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 21,
    club: "Mako Athletics",
    entryTotal: 272,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1071152",
    name: "Brendan Giddings",
    sessionNumber: 30,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 31,
    club: "Unaffiliated",
    entryTotal: 268,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1068396",
    name: "Jacob Echols",
    sessionNumber: 30,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 21,
    club: "Rise Weightlifting",
    entryTotal: 263,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1070099",
    name: "Alexander Truisi",
    sessionNumber: 36,
    sessionPlatform: "Blue",
    weightClass: "71",
  },
  {
    adaptive: false,
    age: 24,
    club: "Unaffiliated",
    entryTotal: 305,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1078797",
    name: "Michael O'Connor",
    sessionNumber: 41,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 26,
    club: "1Kilo",
    entryTotal: 310,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1051014",
    name: "Austin Davis",
    sessionNumber: 41,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 26,
    club: "Unaffiliated",
    entryTotal: 300,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1004359",
    name: "David Izarraras",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 34,
    club: "PARAMOUNT BARBELL CLUB",
    entryTotal: 295,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1041015",
    name: "Tanner Sturm",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 32,
    club: "PARAMOUNT BARBELL CLUB",
    entryTotal: 290,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1019639",
    name: "Jacob Marks",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 28,
    club: "Gryphon Strength Barbell",
    entryTotal: 290,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "218932",
    name: "Christian Tsakanikas",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 34,
    club: "Rise Weightlifting",
    entryTotal: 289,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1064676",
    name: "Mike Fleming",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 30,
    club: "CALPIANS WLC",
    entryTotal: 360,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "155457",
    name: "Daniel Wiitanen",
    sessionNumber: 42,
    sessionPlatform: "Blue",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 31,
    club: "MILWAUKEE BARBELL WEIGHTLIFTING CLUB",
    entryTotal: 340,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1026239",
    name: "Charles Shervheim",
    sessionNumber: 42,
    sessionPlatform: "Blue",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 25,
    club: "Lowcountry Barbell",
    entryTotal: 330,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1056211",
    name: "Jaimerius Williams",
    sessionNumber: 42,
    sessionPlatform: "Blue",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 31,
    club: "Unaffiliated",
    entryTotal: 308,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "201423",
    name: "Benson Robles",
    sessionNumber: 33,
    sessionPlatform: "Red",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 21,
    club: "Concordia University Weightlifting",
    entryTotal: 305,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1066264",
    name: "Enzo Mancini",
    sessionNumber: 33,
    sessionPlatform: "Red",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 30,
    club: "Unaffiliated",
    entryTotal: 300,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "208342",
    name: "William Palumbo",
    sessionNumber: 33,
    sessionPlatform: "Red",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 30,
    club: "CHFP WEIGHTLIFTING CLUB",
    entryTotal: 280,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1069748",
    name: "James Sayger",
    sessionNumber: 39,
    sessionPlatform: "White",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 33,
    club: "POWER AND GRACE PERFORMANCE.",
    entryTotal: 325,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1036060",
    name: "Jacob Cluff",
    sessionNumber: 33,
    sessionPlatform: "Blue",
    weightClass: "110",
  },
  {
    adaptive: false,
    age: 31,
    club: "Ithaca Weightlifting",
    entryTotal: 315,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1004500",
    name: "Benjamin Brancaleon",
    sessionNumber: 33,
    sessionPlatform: "Blue",
    weightClass: "110",
  },
  {
    adaptive: false,
    age: 33,
    club: "Lenka's Lifting Club",
    entryTotal: 365,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1071785",
    name: "Kaleb Wendricks",
    sessionNumber: 45,
    sessionPlatform: "Red",
    weightClass: "+110",
  },
  {
    adaptive: false,
    age: 34,
    club: "UCLA Weightlifting Club",
    entryTotal: 320,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1062292",
    name: "Jake Anderson",
    sessionNumber: 45,
    sessionPlatform: "Red",
    weightClass: "+110",
  },
  {
    adaptive: false,
    age: 29,
    club: "Unaffiliated",
    entryTotal: 310,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "218620",
    name: "Dustin Baranowski",
    sessionNumber: 45,
    sessionPlatform: "Red",
    weightClass: "+110",
  },
  {
    adaptive: false,
    age: 28,
    club: "Vardanian Weightlifting",
    entryTotal: 192,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1055809",
    name: "Andi Johnson",
    sessionNumber: 39,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 30,
    club: "Bexar Barbell",
    entryTotal: 182,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1054656",
    name: "Talley Halvorson",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 31,
    club: "True Strength Performance Weightlifting",
    entryTotal: 200,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1062467",
    name: "Keaton Poppe",
    sessionNumber: 34,
    sessionPlatform: "Red",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 28,
    club: "Pinnacle Weightlifting",
    entryTotal: 282,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1070034",
    name: "Ethan Durant-Childress",
    sessionNumber: 38,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 29,
    club: "Rise Weightlifting",
    entryTotal: 148,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1043848",
    name: "Sarah Hellwig",
    sessionNumber: 44,
    sessionPlatform: "Red",
    weightClass: "58",
  },
  {
    adaptive: false,
    age: 33,
    club: "TEAM TEXAS",
    entryTotal: 320,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1011225",
    name: "Douglas Ligon",
    sessionNumber: 33,
    sessionPlatform: "Blue",
    weightClass: "110",
  },
  {
    adaptive: false,
    age: 33,
    club: "EAST COAST GOLD W/L TEAM",
    entryTotal: 201,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1064301",
    name: "Brianna Chu",
    sessionNumber: 40,
    sessionPlatform: "Red",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 30,
    club: "HEAVY METAL BARBELL",
    entryTotal: 188,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1031334",
    name: "Elena Schorr",
    sessionNumber: 24,
    sessionPlatform: "Blue",
    weightClass: "58",
  },
  {
    adaptive: false,
    age: 34,
    club: "Denver Barbell Club",
    entryTotal: 190,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1046672",
    name: "Adrienne Vogelsang",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 32,
    club: "Unaffiliated",
    entryTotal: 220,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1055790",
    name: "Sarah Barnett",
    sessionNumber: 42,
    sessionPlatform: "Red",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 37,
    club: "RVA Weightlifting",
    entryTotal: 195,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1056680",
    name: "LeKiesha White",
    sessionNumber: 34,
    sessionPlatform: "Red",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 33,
    club: "Lowcountry Barbell",
    entryTotal: 220,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1012701",
    name: "Alexander El",
    sessionNumber: 25,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 33,
    club: "Mako Athletics",
    entryTotal: 290,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1041428",
    name: "Nathan Moore",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 31,
    club: "Unaffiliated",
    entryTotal: 304,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "214920",
    name: "Valera ` Djaghouri",
    sessionNumber: 33,
    sessionPlatform: "Red",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 31,
    club: "Fourteen Forty Collective",
    entryTotal: 182,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1031798",
    name: "Jeanna Onishi",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 30,
    club: "Fourteen Forty Collective",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1053985",
    name: "Kelsey Koontz",
    sessionNumber: 40,
    sessionPlatform: "White",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 29,
    club: "Vardanian Weightlifting",
    entryTotal: 205,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1077563",
    name: "Marissa DelGado",
    sessionNumber: 45,
    sessionPlatform: "Blue",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 21,
    club: "Concordia University Weightlifting",
    entryTotal: 245,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1031940",
    name: "Kaiden Mima",
    sessionNumber: 36,
    sessionPlatform: "Blue",
    weightClass: "60",
  },
  {
    adaptive: false,
    age: 22,
    club: "Ritual Weightlifting",
    entryTotal: 300,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1008851",
    name: "Hampton Morris",
    sessionNumber: 36,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 34,
    club: "Tri State Barbell",
    entryTotal: 270,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1053099",
    name: "Stephen Neer",
    sessionNumber: 30,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 27,
    club: "GARAGE STRENGTH",
    entryTotal: 310,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1060576",
    name: "Ivan Escott",
    sessionNumber: 41,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 23,
    club: "STONEAGE WEIGHTLIFTING CLUB",
    entryTotal: 300,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1003133",
    name: "Trevor Owens",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 27,
    club: "Vardanian Weightlifting",
    entryTotal: 365,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1043909",
    name: "Kyle Schulman",
    sessionNumber: 45,
    sessionPlatform: "Red",
    weightClass: "+110",
  },
  {
    adaptive: false,
    age: 31,
    club: "Unaffiliated",
    entryTotal: 175,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1020820",
    name: "Angela Gallegos",
    sessionNumber: 24,
    sessionPlatform: "Blue",
    weightClass: "58",
  },
  {
    adaptive: false,
    age: 29,
    club: "Unaffiliated",
    entryTotal: 212,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1043944",
    name: "Casey Aguilar-Gervase",
    sessionNumber: 40,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 32,
    club: "Fourteen Forty Collective",
    entryTotal: 190,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1052229",
    name: "Donisha Traver",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 24,
    club: "STONEAGE WEIGHTLIFTING CLUB",
    entryTotal: 185,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "199382",
    name: "Ava Oteri",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 39,
    club: "HEAVY METAL BARBELL",
    entryTotal: 215,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "169822",
    name: "Tayler Harris",
    sessionNumber: 41,
    sessionPlatform: "Blue",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 33,
    club: "EAST COAST GOLD W/L TEAM",
    entryTotal: 205,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1025226",
    name: "Emma Hoffman",
    sessionNumber: 32,
    sessionPlatform: "White",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 29,
    club: "TEAM BLASTOFF",
    entryTotal: 185,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1011601",
    name: "Hannah Brennan",
    sessionNumber: 32,
    sessionPlatform: "White",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 28,
    club: "Oly Concepts",
    entryTotal: 197,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "195177",
    name: "Autumn Makins-Null",
    sessionNumber: 34,
    sessionPlatform: "Red",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 35,
    club: "Fourteen Forty Collective",
    entryTotal: 215,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1040087",
    name: "Timothy Luistro",
    sessionNumber: 22,
    sessionPlatform: "White",
    weightClass: "60",
  },
  {
    adaptive: false,
    age: 30,
    club: "EAST COAST GOLD W/L TEAM",
    entryTotal: 255,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1017543",
    name: "Quinn Kashishian",
    sessionNumber: 36,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 29,
    club: "Jacksonville Weightlifting",
    entryTotal: 280,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1068494",
    name: "Luc Spalding",
    sessionNumber: 38,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 33,
    club: "Unaffiliated",
    entryTotal: 275,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1008072",
    name: "Alexander Souvall",
    sessionNumber: 30,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 31,
    club: "Unaffiliated",
    entryTotal: 260,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1063520",
    name: "Andrew Raudabaugh",
    sessionNumber: 30,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 31,
    club: "Mach10 Weightlifting Club",
    entryTotal: 290,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1017089",
    name: "Alexander Chiang",
    sessionNumber: 33,
    sessionPlatform: "Blue",
    weightClass: "110",
  },
  {
    adaptive: false,
    age: 33,
    club: "BlueWave Weightlifting",
    entryTotal: 139,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1049227",
    name: "Sarah Morris",
    sessionNumber: 36,
    sessionPlatform: "White",
    weightClass: "48",
  },
  {
    adaptive: false,
    age: 23,
    club: "Unaffiliated",
    entryTotal: 184,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1010406",
    name: "D. Irizarry",
    sessionNumber: 37,
    sessionPlatform: "Red",
    weightClass: "53",
  },
  {
    adaptive: false,
    age: 34,
    club: "Unaffiliated",
    entryTotal: 166,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "208127",
    name: "Sarah Wright",
    sessionNumber: 37,
    sessionPlatform: "Red",
    weightClass: "53",
  },
  {
    adaptive: false,
    age: 36,
    club: "HARRISBURG WEIGHTLIFTING CLUB",
    entryTotal: 165,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "184651",
    name: "Katherine Lee",
    sessionNumber: 37,
    sessionPlatform: "Red",
    weightClass: "53",
  },
  {
    adaptive: false,
    age: 42,
    club: "Unaffiliated",
    entryTotal: 148,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1078809",
    name: "Amy Smith",
    sessionNumber: 44,
    sessionPlatform: "Red",
    weightClass: "53",
  },
  {
    adaptive: false,
    age: 22,
    club: "HASSLE FREE BBC",
    entryTotal: 180,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1008993",
    name: "haley trinh",
    sessionNumber: 24,
    sessionPlatform: "Blue",
    weightClass: "58",
  },
  {
    adaptive: false,
    age: 34,
    club: "Samsara Weightlifting Club",
    entryTotal: 175,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1032784",
    name: "Maria Hayden",
    sessionNumber: 24,
    sessionPlatform: "Blue",
    weightClass: "58",
  },
  {
    adaptive: false,
    age: 34,
    club: "MURDER OF CROWS",
    entryTotal: 170,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1034914",
    name: "Jessica Rodriguez",
    sessionNumber: 37,
    sessionPlatform: "Blue",
    weightClass: "58",
  },
  {
    adaptive: false,
    age: 26,
    club: "Denver Barbell Club",
    entryTotal: 165,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1064699",
    name: "Megan Schroeder",
    sessionNumber: 37,
    sessionPlatform: "Blue",
    weightClass: "58",
  },
  {
    adaptive: false,
    age: 28,
    club: "TEAM BLASTOFF",
    entryTotal: 164,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1024000",
    name: "Claire Vahary",
    sessionNumber: 37,
    sessionPlatform: "Blue",
    weightClass: "58",
  },
  {
    adaptive: false,
    age: 27,
    club: "HASSLE FREE BBC",
    entryTotal: 211,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1053971",
    name: "Jamie Hegg",
    sessionNumber: 38,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 30,
    club: "HEAVY METAL BARBELL",
    entryTotal: 198,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1034657",
    name: "Siera Schuster",
    sessionNumber: 38,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 21,
    club: "Bexar Barbell",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1031574",
    name: "Kailey Papas",
    sessionNumber: 40,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 28,
    club: "Unaffiliated",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "218788",
    name: "Meredith Alwine",
    sessionNumber: 40,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 25,
    club: "Fourteen Forty Collective",
    entryTotal: 195,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1063776",
    name: "Lucie Gehringer",
    sessionNumber: 39,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 26,
    club: "Myriad Weightlifting",
    entryTotal: 186,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1040898",
    name: "Erica Sheagley",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 34,
    club: "West Coast Weightlifting",
    entryTotal: 215,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1020750",
    name: "Darci Molina",
    sessionNumber: 41,
    sessionPlatform: "Blue",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 31,
    club: "Bexar Barbell",
    entryTotal: 215,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1019928",
    name: "Estelle Rohr",
    sessionNumber: 41,
    sessionPlatform: "Blue",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 28,
    club: "Vardanian Weightlifting",
    entryTotal: 200,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "162808",
    name: "Erin Amos",
    sessionNumber: 40,
    sessionPlatform: "Red",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 22,
    club: "University of Colorado Barbell",
    entryTotal: 200,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1057676",
    name: "Kat Carter",
    sessionNumber: 40,
    sessionPlatform: "Red",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 31,
    club: "POWER AND GRACE PERFORMANCE.",
    entryTotal: 195,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1045235",
    name: "Ashlie Pankonin",
    sessionNumber: 40,
    sessionPlatform: "Red",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 34,
    club: "ATLANTA PERFORMANCE",
    entryTotal: 193,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1049231",
    name: "Aleigh Moore",
    sessionNumber: 40,
    sessionPlatform: "Red",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 24,
    club: "Team Strength Works",
    entryTotal: 230,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1063674",
    name: "Ava Biesterfeld",
    sessionNumber: 42,
    sessionPlatform: "Red",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 26,
    club: "Unaffiliated",
    entryTotal: 245,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1063866",
    name: "Caitlin Thilges",
    sessionNumber: 45,
    sessionPlatform: "Blue",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 32,
    club: "Unaffiliated",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1016550",
    name: "Kristen Erickson",
    sessionNumber: 45,
    sessionPlatform: "Blue",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 39,
    club: "Unaffiliated",
    entryTotal: 203,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1085437",
    name: "Dowling Andrea",
    sessionNumber: 43,
    sessionPlatform: "White",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 38,
    club: "EAST COAST GOLD W/L TEAM",
    entryTotal: 175,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1075584",
    name: "Rebecca Dublin",
    sessionNumber: 43,
    sessionPlatform: "White",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 22,
    club: "MAX KANE BARBELL",
    entryTotal: 280,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1057975",
    name: "gabe chhum",
    sessionNumber: 36,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 25,
    club: "ATHLETIC LAB WLC",
    entryTotal: 235,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1058490",
    name: "Chase Overpeck",
    sessionNumber: 35,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 24,
    club: "Gator Weightlifting",
    entryTotal: 220,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1044798",
    name: "Jakobe Morgan",
    sessionNumber: 25,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 22,
    club: "Bexar Barbell",
    entryTotal: 290,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1071261",
    name: "Nathan Gonzaga",
    sessionNumber: 38,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 30,
    club: "Gryphon Strength Barbell",
    entryTotal: 290,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1005442",
    name: "Marc Marquez",
    sessionNumber: 36,
    sessionPlatform: "Blue",
    weightClass: "71",
  },
  {
    adaptive: false,
    age: 20,
    club: "Team Strength Works",
    entryTotal: 280,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1066907",
    name: "Zakaria Naas",
    sessionNumber: 38,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 28,
    club: "Unaffiliated",
    entryTotal: 275,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1001425",
    name: "Jack Walbye",
    sessionNumber: 30,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 35,
    club: "TEXAS BARBELL CLUB",
    entryTotal: 265,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "210059",
    name: "Greg Cook",
    sessionNumber: 30,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 19,
    club: "GARAGE STRENGTH",
    entryTotal: 334,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1009548",
    name: "Ryan McDonald",
    sessionNumber: 41,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 29,
    club: "Austin Barbell",
    entryTotal: 300,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1035928",
    name: "Marcus Leydecker",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 27,
    club: "Myriad Weightlifting",
    entryTotal: 300,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1015325",
    name: "Elias Talcott",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 28,
    club: "Unaffiliated",
    entryTotal: 270,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1058751",
    name: "Jacob Johnsson",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 25,
    club: "EAST COAST GOLD W/L TEAM",
    entryTotal: 335,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1014341",
    name: "Chrisanto D'Agostino",
    sessionNumber: 42,
    sessionPlatform: "Blue",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 36,
    club: "HEAVY METAL BARBELL",
    entryTotal: 335,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1035283",
    name: "Daniel Dodd",
    sessionNumber: 42,
    sessionPlatform: "Blue",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 31,
    club: "Columbus Weightlifting",
    entryTotal: 320,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1052075",
    name: "Luke MacLennan",
    sessionNumber: 42,
    sessionPlatform: "Blue",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 26,
    club: "HASSLE FREE BBC",
    entryTotal: 300,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1070935",
    name: "Aidan Kung",
    sessionNumber: 33,
    sessionPlatform: "Red",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 35,
    club: "Unaffiliated",
    entryTotal: 335,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1002720",
    name: "Jacob Mattrella",
    sessionNumber: 44,
    sessionPlatform: "Red",
    weightClass: "110",
  },
  {
    adaptive: false,
    age: 32,
    club: "Heartland Strength",
    entryTotal: 309,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1020803",
    name: "Beau Brown",
    sessionNumber: 33,
    sessionPlatform: "Blue",
    weightClass: "110",
  },
  {
    adaptive: false,
    age: 39,
    club: "HEAVY METAL BARBELL",
    entryTotal: 360,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "131110",
    name: "Caine Wilkes",
    sessionNumber: 45,
    sessionPlatform: "Red",
    weightClass: "+110",
  },
  {
    adaptive: false,
    age: 35,
    club: "Rising Tide Weightlifting",
    entryTotal: 350,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1008163",
    name: "Dimitri Albury",
    sessionNumber: 45,
    sessionPlatform: "Red",
    weightClass: "+110",
  },
  {
    adaptive: false,
    age: 30,
    club: "Team Strength Works",
    entryTotal: 320,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1073307",
    name: "Andrew Montoya",
    sessionNumber: 45,
    sessionPlatform: "Red",
    weightClass: "+110",
  },
  {
    adaptive: false,
    age: 28,
    club: "Orlando Strength",
    entryTotal: 140,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1017520",
    name: "Aria Zayed",
    sessionNumber: 36,
    sessionPlatform: "White",
    weightClass: "48",
  },
  {
    adaptive: false,
    age: 34,
    club: "Unaffiliated",
    entryTotal: 175,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1051395",
    name: "Veronica Bagundes",
    sessionNumber: 37,
    sessionPlatform: "Red",
    weightClass: "53",
  },
  {
    adaptive: false,
    age: 21,
    club: "Bexar Barbell",
    entryTotal: 200,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1025560",
    name: "Anna Rucker",
    sessionNumber: 38,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 32,
    club: "Unaffiliated",
    entryTotal: 196,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1058891",
    name: "Madison Johnston",
    sessionNumber: 38,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 35,
    club: "Tri State Barbell",
    entryTotal: 185,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1065518",
    name: "Lisa Ho",
    sessionNumber: 35,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 25,
    club: "Unaffiliated",
    entryTotal: 180,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "210346",
    name: "Kathryn Rose",
    sessionNumber: 35,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 26,
    club: "Fourteen Forty Collective",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1026578",
    name: "Kristina Robinson",
    sessionNumber: 40,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 23,
    club: "Unaffiliated",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1060757",
    name: "Addie Anderson",
    sessionNumber: 40,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 35,
    club: "EAST COAST GOLD W/L TEAM",
    entryTotal: 183,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1053538",
    name: "Melissa Salazar",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 35,
    club: "Bexar Barbell",
    entryTotal: 183,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1015165",
    name: "Gretchen Stolte",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 30,
    club: "Unaffiliated",
    entryTotal: 230,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "214993",
    name: "Shacasia Johnson",
    sessionNumber: 41,
    sessionPlatform: "Blue",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 24,
    club: "DSSC Weightlifting",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1044061",
    name: "Carly Brown",
    sessionNumber: 41,
    sessionPlatform: "Blue",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 30,
    club: "PROJECT LIFT",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1036400",
    name: "Francesca Dooris",
    sessionNumber: 41,
    sessionPlatform: "Blue",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 29,
    club: "Samsara Weightlifting Club",
    entryTotal: 200,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1030233",
    name: "Victoria Fries",
    sessionNumber: 40,
    sessionPlatform: "Red",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 28,
    club: "Unaffiliated",
    entryTotal: 226,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1031641",
    name: "Stephanie Gousse",
    sessionNumber: 45,
    sessionPlatform: "Blue",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 32,
    club: "EAST COAST GOLD W/L TEAM",
    entryTotal: 208,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1039016",
    name: "Jennifer Galemmo",
    sessionNumber: 45,
    sessionPlatform: "Blue",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 19,
    club: "Unaffiliated",
    entryTotal: 260,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1070848",
    name: "Bryson Brown",
    sessionNumber: 36,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 34,
    club: "PHILADELPHIA BARBELL",
    entryTotal: 245,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "174251",
    name: "Christopher Camenares",
    sessionNumber: 25,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 28,
    club: "Bowen Elite Weightlifting",
    entryTotal: 270,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1043376",
    name: "Ethan Bowen",
    sessionNumber: 36,
    sessionPlatform: "Blue",
    weightClass: "71",
  },
  {
    adaptive: false,
    age: 31,
    club: "Unaffiliated",
    entryTotal: 288,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "212416",
    name: "Dallas Tada",
    sessionNumber: 38,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 29,
    club: "MURDER OF CROWS",
    entryTotal: 272,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1056960",
    name: "Miguel Lavarro",
    sessionNumber: 30,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 29,
    club: "Unaffiliated",
    entryTotal: 290,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1043764",
    name: "Jerod Peters",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 30,
    club: "Unaffiliated",
    entryTotal: 280,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "185861",
    name: "Troy Fries",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 20,
    club: "GARAGE STRENGTH",
    entryTotal: 332,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "215112",
    name: "Kyle Martin",
    sessionNumber: 42,
    sessionPlatform: "Blue",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 21,
    club: "Mako Athletics",
    entryTotal: 290,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1073048",
    name: "Jackson Leonard",
    sessionNumber: 39,
    sessionPlatform: "White",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 27,
    club: "Southern California Weightlifting Club",
    entryTotal: 310,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "211745",
    name: "Denali Scoular",
    sessionNumber: 33,
    sessionPlatform: "Blue",
    weightClass: "110",
  },
  {
    adaptive: false,
    age: 22,
    club: "Unaffiliated",
    entryTotal: 310,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1016964",
    name: "Timothy Davis",
    sessionNumber: 33,
    sessionPlatform: "Blue",
    weightClass: "110",
  },
  {
    adaptive: false,
    age: 27,
    club: "Glass City Weightlifting",
    entryTotal: 345,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1040724",
    name: "Matthew Naugle",
    sessionNumber: 45,
    sessionPlatform: "Red",
    weightClass: "+110",
  },
  {
    adaptive: false,
    age: 32,
    club: "Unaffiliated",
    entryTotal: 310,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1010593",
    name: "Anthony Owens",
    sessionNumber: 45,
    sessionPlatform: "Red",
    weightClass: "+110",
  },
  {
    adaptive: false,
    age: 37,
    club: "Unaffiliated",
    entryTotal: 205,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "141793",
    name: "Mahassen Paiva",
    sessionNumber: 40,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 40,
    club: "PARAMOUNT BARBELL CLUB",
    entryTotal: 176,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1003376",
    name: "Eve Goldsher",
    sessionNumber: 25,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 25,
    club: "Oly Concepts",
    entryTotal: 195,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1055079",
    name: "Grace Bustamante",
    sessionNumber: 40,
    sessionPlatform: "White",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 26,
    club: "Freedom Weightlifting",
    entryTotal: 205,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "215456",
    name: "Madeline Staniszewski",
    sessionNumber: 38,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 30,
    club: "Florida Elite",
    entryTotal: 190,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "186129",
    name: "Angelique Matsushima",
    sessionNumber: 35,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 22,
    club: "Sanctuary Barbell",
    entryTotal: 250,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1058355",
    name: "Katelyn Witte",
    sessionNumber: 42,
    sessionPlatform: "Red",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 28,
    club: "Unaffiliated",
    entryTotal: 276,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1014939",
    name: "Jacob OConnor",
    sessionNumber: 30,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 28,
    club: "VERO BEACH WEIGHTLIFTING",
    entryTotal: 290,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1072741",
    name: "Jeremy Williams",
    sessionNumber: 39,
    sessionPlatform: "White",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 26,
    club: "EAST COAST GOLD W/L TEAM",
    entryTotal: 310,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1047819",
    name: "Colton Krueger",
    sessionNumber: 33,
    sessionPlatform: "Blue",
    weightClass: "110",
  },
  {
    adaptive: false,
    age: 22,
    club: "Mars Hill University",
    entryTotal: 240,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1067579",
    name: "Nahshon Paul",
    sessionNumber: 28,
    sessionPlatform: "Blue",
    weightClass: "71",
  },
  {
    adaptive: false,
    age: 21,
    club: "Optimus Barbell Club",
    entryTotal: 240,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1046180",
    name: "Sophia Shaft",
    sessionNumber: 38,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 21,
    club: "Oly Concepts",
    entryTotal: 212,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1061724",
    name: "Nicole Caamano",
    sessionNumber: 40,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 31,
    club: "Unaffiliated",
    entryTotal: 175,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1078562",
    name: "Aarynn Crawley",
    sessionNumber: 36,
    sessionPlatform: "Red",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 21,
    club: "GARAGE STRENGTH",
    entryTotal: 270,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1065230",
    name: "Evan Gehret",
    sessionNumber: 36,
    sessionPlatform: "Blue",
    weightClass: "71",
  },
  {
    adaptive: false,
    age: 35,
    club: "Unaffiliated",
    entryTotal: 135,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1052471",
    name: "tiffany leung",
    sessionNumber: 36,
    sessionPlatform: "White",
    weightClass: "48",
  },
  {
    adaptive: false,
    age: 32,
    club: "BlueWave Weightlifting",
    entryTotal: 300,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "206955",
    name: "Ruben Martinez",
    sessionNumber: 33,
    sessionPlatform: "Red",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 22,
    club: "ALPHA BARBELL",
    entryTotal: 227,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1012015",
    name: "Katharine Estep",
    sessionNumber: 38,
    sessionPlatform: "Red",
    weightClass: "63",
  },
  {
    adaptive: false,
    age: 33,
    club: "1Kilo",
    entryTotal: 215,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1021432",
    name: "Alexa Snyder",
    sessionNumber: 18,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 29,
    club: "Tank Performance and Weightlifting",
    entryTotal: 190,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1043954",
    name: "Tiffany Roberts",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 36,
    club: "EAST COAST GOLD W/L TEAM",
    entryTotal: 180,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1058160",
    name: "MATTIE FLICKINGER",
    sessionNumber: 27,
    sessionPlatform: "White",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 35,
    club: "Fourteen Forty Collective",
    entryTotal: 200,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1045817",
    name: "Haley McDaniel",
    sessionNumber: 40,
    sessionPlatform: "White",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 31,
    club: "Fourteen Forty Collective",
    entryTotal: 335,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1041830",
    name: "Joshua Magee",
    sessionNumber: 44,
    sessionPlatform: "Red",
    weightClass: "110",
  },
  {
    adaptive: false,
    age: 27,
    club: "GARAGE STRENGTH",
    entryTotal: 160,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1031803",
    name: "Virginie Beljour",
    sessionNumber: 44,
    sessionPlatform: "Red",
    weightClass: "48",
  },
  {
    adaptive: false,
    age: 22,
    club: "Fourteen Forty Collective",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1048972",
    name: "Miranda Ulrey",
    sessionNumber: 24,
    sessionPlatform: "Blue",
    weightClass: "58",
  },
  {
    adaptive: false,
    age: 28,
    club: "Oly Concepts",
    entryTotal: 185,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1063275",
    name: "Alexis Boutchie",
    sessionNumber: 32,
    sessionPlatform: "White",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 26,
    club: "EAST COAST GOLD W/L TEAM",
    entryTotal: 180,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1081441",
    name: "Ryan Westpfahl",
    sessionNumber: 32,
    sessionPlatform: "White",
    weightClass: "77",
  },
  {
    adaptive: false,
    age: 21,
    club: "LINDENWOOD LIONS",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1077665",
    name: "Chealsea Enemor",
    sessionNumber: 45,
    sessionPlatform: "Blue",
    weightClass: "+86",
  },
  {
    adaptive: false,
    age: 28,
    club: "PHILADELPHIA BARBELL",
    entryTotal: 229,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "175740",
    name: "Estevan Soto",
    sessionNumber: 35,
    sessionPlatform: "Blue",
    weightClass: "60",
  },
  {
    adaptive: false,
    age: 39,
    club: "LBH OF NYC DEPT OF PARKS",
    entryTotal: 233,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "179013",
    name: "Dean Otsuka",
    sessionNumber: 35,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 26,
    club: "Unaffiliated",
    entryTotal: 270,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1023329",
    name: "Blace Eckols",
    sessionNumber: 30,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 30,
    club: "BlueWave Weightlifting",
    entryTotal: 345,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1052501",
    name: "Brandon Victorian",
    sessionNumber: 41,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 24,
    club: "Fourteen Forty Collective",
    entryTotal: 320,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1066091",
    name: "Wyatt Coffey",
    sessionNumber: 41,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 29,
    club: "Unaffiliated",
    entryTotal: 360,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1017324",
    name: "Cesar Flores",
    sessionNumber: 45,
    sessionPlatform: "Red",
    weightClass: "+110",
  },
  {
    adaptive: false,
    age: 30,
    club: "Providence Barbell Club",
    entryTotal: 146,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1064794",
    name: "Lucy Lapane",
    sessionNumber: 36,
    sessionPlatform: "White",
    weightClass: "48",
  },
  {
    adaptive: false,
    age: 32,
    club: "Sanctuary Barbell",
    entryTotal: 170,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1071061",
    name: "Mandy O\u2019Shell",
    sessionNumber: 37,
    sessionPlatform: "Blue",
    weightClass: "58",
  },
  {
    adaptive: false,
    age: 28,
    club: "CATALYST ATHLETICS",
    entryTotal: 205,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "195112",
    name: "Nairobi Romero",
    sessionNumber: 40,
    sessionPlatform: "Blue",
    weightClass: "69",
  },
  {
    adaptive: false,
    age: 24,
    club: "GARAGE STRENGTH",
    entryTotal: 240,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1027093",
    name: "Anna McElderry",
    sessionNumber: 42,
    sessionPlatform: "Red",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 23,
    club: "HEAVY METAL BARBELL",
    entryTotal: 210,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1051520",
    name: "Harley Creech",
    sessionNumber: 40,
    sessionPlatform: "White",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 20,
    club: "MYLES AHEAD WEIGHTLIFTING",
    entryTotal: 269,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1075231",
    name: "Christopher Cruz",
    sessionNumber: 36,
    sessionPlatform: "Blue",
    weightClass: "65",
  },
  {
    adaptive: false,
    age: 26,
    club: "Ablaze Barbell",
    entryTotal: 258,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "221413",
    name: "Bryce Mattos",
    sessionNumber: 30,
    sessionPlatform: "Blue",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 29,
    club: "GREEN BAY BARBELL",
    entryTotal: 250,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1039273",
    name: "Andre Sanchez",
    sessionNumber: 27,
    sessionPlatform: "Red",
    weightClass: "79",
  },
  {
    adaptive: false,
    age: 33,
    club: "Myriad Weightlifting",
    entryTotal: 290,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1016271",
    name: "Griffin Elbert",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 28,
    club: "HASSLE FREE BBC",
    entryTotal: 275,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1071848",
    name: "Wesley Hu",
    sessionNumber: 32,
    sessionPlatform: "Red",
    weightClass: "88",
  },
  {
    adaptive: false,
    age: 23,
    club: "Fourteen Forty Collective",
    entryTotal: 340,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "179975",
    name: "Morgan McCullough",
    sessionNumber: 42,
    sessionPlatform: "Blue",
    weightClass: "94",
  },
  {
    adaptive: false,
    age: 31,
    club: "Unaffiliated",
    entryTotal: 390,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1009887",
    name: "Keiser Witte",
    sessionNumber: 45,
    sessionPlatform: "Red",
    weightClass: "+110",
  },
  {
    adaptive: false,
    age: 20,
    club: "LINDENWOOD LIONS",
    entryTotal: 245,
    gender: "Female",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1055916",
    name: "Ella Nicholson",
    sessionNumber: 42,
    sessionPlatform: "Red",
    weightClass: "86",
  },
  {
    adaptive: false,
    age: 35,
    club: "PHILADELPHIA BARBELL",
    entryTotal: 309,
    gender: "Male",
    meet: "2026 USA Weightlifting National Championships, Powered by Rogue Fitness",
    memberId: "1002849",
    name: "Onzy Elam",
    sessionNumber: 33,
    sessionPlatform: "Red",
    weightClass: "94",
  }
];
