
auth.token=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

defaults.org=meetcal-llc
defaults.project=react-native

defaults.url=https://sentry.io/
